### ISSUE TITLE
[REQUEST]: Subdomain for ML Bhopal Community

### ISSUE THREAD

**Issue by MLBhopal** [ml-comm/ddns#16]
### Describe your request

We need a subdomain for the ML Bhopal community as it will enhance our community’s visibility, credibility, and engagement. It will serve as a centralized platform for sharing resources, event updates, and collaboration opportunities, contributing to the growth of the local AI/ML community.

### Subdomain

bhopal

### Purpose

The bhopal.mlcommunity.dev subdomain will be dedicated to hosting the ML Bhopal community’s official website, offering access to resources, event updates, and networking opportunities for members. It will serve as a professional platform to facilitate collaboration, knowledge sharing, and community engagement within the Bhopal tech community

### Socials

Github : @MLBhopal
Linkedin : https://www.linkedin.com/company/mlbhopal/

**Comment by BRAVO68WEB** [comment]
@MLBhopal 

Can you share your current website?

**Comment by MLBhopal** [comment]
https://ml-bhopal-website.vercel.app/

**Comment by BRAVO68WEB** [comment]
Yes, I approved your request

**Comment by BRAVO68WEB** [comment]
No need to open a new issue for future queries related to this subdomain. Just create PR and mention "#16" in the related issues section. 😃
