### ISSUE TITLE
[REQUEST]: Request for TensorFlow User Group Ghaziabad's subdomain, i.e ghaziabad.mlcommunity.dev

### ISSUE THREAD

**Issue by AniketRajSingh** [ml-comm/ddns#17]
### Describe your request

The TFUG Ghaziabad community requires the subdomain ghaziabad.mlcommunity.dev for our upcoming website. This platform will be dedicated to raising awareness about the activities and initiatives of the machine learning community in the Ghaziabad region.

### Subdomain

ghaziabad.mlcommunity.dev

### Purpose

We aim to host both past and upcoming events for TFUG Ghaziabad, along with additional content such as:

- Event Recaps and Highlights
- Community Initiatives and Projects
- Machine Learning Workshops and Tutorials
- Blog Posts on ML Trends and Innovations
- Member Spotlights and Contributions
- Resources for Learning and Collaboration in ML
- News and Updates from the ML Community

All of this will be showcased on the website to keep the community informed and engaged.

### Project repository link (if any)

https://github.com/TFUG-Ghaziabad/TFUG-Ghaziabad/tree/aniket-master/tfug_ghaziabad

### Additional context

I want to be able to use the A name and AAA names as I am hosting my server on GCP.

### Socials

- [Linkedin](https://www.linkedin.com/company/tensorflow-user-group-ghaziabad/)
- [Github]( https://github.com/TFUG-Ghaziabad/)
- [Instagram](https://www.instagram.com/tfug_ghaziabad/)
- [Twitter](https://twitter.com/tfug_ghaziabad)

**Comment by BRAVO68WEB** [comment]
Sure 👍🏻

**Comment by Ba3a-G** [comment]
Hey @AniketRajSingh,
Looks good. Please go ahead and create a PR with the IP address. 🚀

**Comment by BRAVO68WEB** [comment]
When even you need to update your dns records, just mention "#17" in your PR on top.
